const LANG = {
  // ── Global / Common ──────────────────────────────────────────
  app_name:         { sw: 'MediSauti', en: 'MediSauti' },
  error:            { sw: 'Hitilafu', en: 'Error' },
  success:          { sw: 'Imefanikiwa', en: 'Success' },
  saved:            { sw: 'Imehifadhiwa', en: 'Saved' },
  save:             { sw: 'Hifadhi', en: 'Save' },
  cancel:           { sw: 'Ghairi', en: 'Cancel' },
  delete:           { sw: 'Futa', en: 'Delete' },
  yes:              { sw: 'Ndiyo', en: 'Yes' },
  no:               { sw: 'Hapana', en: 'No' },
  loading:          { sw: 'Inapakia...', en: 'Loading...' },
  swahili:          { sw: 'Kiswahili', en: 'Swahili' },
  english:          { sw: 'Kiingereza', en: 'English' },

  // ── Days ─────────────────────────────────────────────────────
  mon:              { sw: 'Jnt', en: 'Mon' },
  tue:              { sw: 'Jmn', en: 'Tue' },
  wed:              { sw: 'Jtt', en: 'Wed' },
  thu:              { sw: 'Alh', en: 'Thu' },
  fri:              { sw: 'Ijm', en: 'Fri' },
  sat:              { sw: 'Jum', en: 'Sat' },
  sun:              { sw: 'Jpi', en: 'Sun' },

  // ── Landing Screen ───────────────────────────────────────────
  tagline:          { sw: 'Dawa yako, afya yako', en: 'Your meds, your health' },
  landing_desc:     { sw: 'Panga ratiba ya dawa zako, pata vikumbusho, na fuata uzingativu wako kwa urahisi.', en: 'Schedule your medications, get reminders, and track your adherence easily.' },
  login:            { sw: 'Ingia', en: 'Login' },
  login_sub:        { sw: 'Tumia PIN au alama ya uso', en: 'Use PIN or biometrics' },
  or_divider:       { sw: 'AU', en: 'OR' },
  register:         { sw: 'Jisajili', en: 'Register' },
  register_sub:     { sw: 'Unda akaunti mpya', en: 'Create a new account' },

  // ── Auth Screen ──────────────────────────────────────────────
  auth_biometric_prompt:   { sw: 'Ingiza alama ya uso au kidole', en: 'Authenticate to continue' },
  auth_use_pin:            { sw: 'Tumia PIN', en: 'Use PIN' },
  bio_opt_in:              { sw: 'Washa kuingia kwa alama ya uso / kidole?', en: 'Enable face / fingerprint login?' },
  bio_opt_in_desc:         { sw: 'Ingia kwa haraka kwa kutumia kifaa chako.', en: 'Log in faster using your device.' },
  bio_enabled_label:       { sw: 'Imewashwa', en: 'Enabled' },
  bio_enabled_desc:        { sw: 'Utatumia alama ya uso / kidole kuingia.', en: 'You will use biometrics to log in.' },
  bio_register_prompt:     { sw: 'Sajili alama ya uso / kidole', en: 'Register face / fingerprint' },
  bio_enrolled:            { sw: 'Imejiandikisha! Sasa utaingia kwa haraka.', en: 'Enrolled! You can now log in faster.' },
  bio_tap_to_login:        { sw: 'Gusa kuingia', en: 'Tap to log in' },
  bio_pref_hint:           { sw: 'Una alama iliyohifadhiwa', en: 'You have biometrics saved' },
  welcome_back:            { sw: 'Karibu tena!', en: 'Welcome back!' },
  fill_all_fields:         { sw: 'Tafadhali jaza sehemu zote.', en: 'Please fill all fields.' },
  pin_mismatch:            { sw: 'PIN hailingani', en: 'PIN Mismatch' },
  pin_mismatch_body:       { sw: 'PIN ulizoingiza hazilingani. Tafadhali jaribu tena.', en: 'The PINs you entered do not match. Please try again.' },
  registration_success:    { sw: 'Umesajiliwa', en: 'Registered' },
  registration_welcome:    { sw: 'Karibu, {name}!', en: 'Welcome, {name}!' },
  invalid_pin:             { sw: 'PIN si sahihi', en: 'Invalid PIN' },
  wrong_pin:               { sw: 'PIN si sahihi', en: 'Wrong PIN' },
  wrong_pin_body:          { sw: 'Umeingiza PIN isiyo sahihi. Tafadhali jaribu tena.', en: 'You entered an incorrect PIN. Please try again.' },
  card_register_title:     { sw: 'Jisajili', en: 'Register' },
  card_register_subtitle:  { sw: 'Tafadhali jaza taarifa zako za matibabu.', en: 'Please fill in your medical information.' },
  label_name:              { sw: 'Jina kamili', en: 'Full name' },
  label_phone:             { sw: 'Nambari ya simu', en: 'Phone number' },
  label_age:               { sw: 'Umri', en: 'Age' },
  label_condition:         { sw: 'Hali ya kiafya', en: 'Medical condition' },
  label_set_pin:           { sw: 'Weka PIN (tarakimu 4)', en: 'Set PIN (4 digits)' },
  label_confirm_pin:       { sw: 'Thibitisha PIN', en: 'Confirm PIN' },
  label_your_pin:          { sw: 'PIN yako', en: 'Your PIN' },
  btn_register:            { sw: 'Jisajili', en: 'Register' },
  card_login_title:        { sw: 'Ingia', en: 'Login' },
  card_login_subtitle:     { sw: 'Ingiza PIN yako au tumia alama ya uso / kidole.', en: 'Enter your PIN or use face/fingerprint to continue.' },
  btn_biometric:           { sw: 'Tumia alama ya uso / kidole', en: 'Use face / fingerprint' },
  or_enter_pin:            { sw: 'AU ingiza PIN', en: 'OR enter PIN' },
  btn_login:               { sw: 'Ingia', en: 'Login' },
  switch_to_register:      { sw: 'Sajili mtumiaji mpya', en: 'Register a new user' },
  placeholder_name:        { sw: 'Mf. Juma Omary', en: 'e.g. Juma Omary' },
  placeholder_phone:       { sw: 'Mf. 0712345678', en: 'e.g. 0712345678' },
  placeholder_age:         { sw: 'Mf. 30', en: 'e.g. 30' },
  placeholder_condition:   { sw: 'Mf. Kisukari', en: 'e.g. Diabetes' },

  // ── Home Screen ──────────────────────────────────────────────
  greeting_morning:        { sw: 'Habari za asubuhi', en: 'Good morning' },
  greeting_afternoon:      { sw: 'Habari za mchana', en: 'Good afternoon' },
  greeting_evening:        { sw: 'Habari za jioni', en: 'Good evening' },
  greeting_night:          { sw: 'Habari za usiku', en: 'Good night' },
  heading_adherence:       { sw: 'Uzingativu wa mwezi', en: 'Monthly adherence' },
  doses_taken_30d:         { sw: 'Dawa zilizonywa (siku 30)', en: 'Doses taken (30d)' },
  missed_30d:              { sw: 'Zilizokosa (siku 30)', en: 'Missed (30d)' },
  next_reminder:           { sw: 'Inayokuja', en: 'Next reminder' },
  this_week:               { sw: 'Wiki hii', en: 'This week' },
  tip_heading:             { sw: 'Kidokezo', en: 'Tip' },
  tip_text:                { sw: 'Kunywa dawa zako pamoja na chakula ili kupunguza usumbufu wa tumbo.', en: 'Take your meds with food to reduce stomach discomfort.' },
  all_medications:         { sw: 'Dawa zote', en: 'All medications' },
  no_meds_added:           { sw: 'Bado hujaongeza dawa.', en: 'No meds added yet.' },
  badge_low_stock:         { sw: 'Inaisha', en: 'Low stock' },
  badge_active:            { sw: 'Inatumika', en: 'Active' },
  trend_great:             { sw: 'Nzuri', en: 'Great' },
  trend_fair:              { sw: 'Wastani', en: 'Fair' },
  trend_low:               { sw: 'Chini', en: 'Low' },
  taken_label:             { sw: 'zimenywa', en: 'taken' },
  missed_label:            { sw: 'zimekosa', en: 'missed' },
  speaking_reminder:       { sw: '"Ni wakati wa kuchukua dawa yako..."', en: '"It is time to take your medication..."' },
  take_all:                { sw: 'Zote', en: 'All' },

  // ── Scan Screen ──────────────────────────────────────────────
  header_scan:             { sw: 'Changanua', en: 'Scan' },
  hero_title:              { sw: 'Sauti ya Dawa', en: 'Voice of Meds' },
  hero_subtitle:           { sw: 'Changanua lebo yako ya dawa kwa kutumia kamera au ingiza kwa mkono.', en: 'Scan your medication label using the camera or enter it manually.' },
  scanning:                { sw: 'Inasoma...', en: 'Scanning...' },
  ocr_ai_title:            { sw: 'Akili Bandia', en: 'AI Parsing' },
  ocr_ai_no_key:           { sw: 'Hakuna ufunguo wa AI. Inatumia uchambuzi wa mitaa (regex). Weka EXPO_PUBLIC_GEMINI_API_KEY au EXPO_PUBLIC_GITHUB_PAT kwenye .env ili kuwezesha.', en: 'No AI key set. Using local regex parsing. Add EXPO_PUBLIC_GEMINI_API_KEY or EXPO_PUBLIC_GITHUB_PAT to .env to enable.' },
  ready_to_scan:           { sw: 'Tayari kuchanganua', en: 'Ready to scan' },
  manual_entry:            { sw: 'Andika Mwenyewe', en: 'Manual Entry' },
  manual_entry_desc:       { sw: 'Ingiza dawa kwa mkono.', en: 'Type medication details manually.' },
  recent_scans:            { sw: 'Historia', en: 'Recent Scans' },
  recent_scans_desc:       { sw: 'Dawa zilizochanganuliwa hivi karibuni.', en: 'Recently scanned medications.' },
  pro_tip_badge:           { sw: 'USHAURI', en: 'PRO TIP' },
  pro_tip_title:           { sw: 'Hakikisha mwanga mzuri', en: 'Ensure good lighting' },
  pro_tip_desc:            { sw: 'Weka chupa ya dawa kwenye eneo lenye mwanga mzuri na ushikilie simu kwa utulivu kwa matokeo bora.', en: 'Place your medicine bottle in a well-lit area and hold your phone steady for best results.' },

  // ── Prescription Screen ──────────────────────────────────────
  header_medications:      { sw: 'Dawa', en: 'Medications' },
  badge_doctor:            { sw: 'Daktari', en: 'Doctor' },
  validation_error:        { sw: 'Tafadhali jaza jina na kipimo cha dawa.', en: 'Please fill drug name and dosage.' },
  saved_success:           { sw: 'Dawa imehifadhiwa kwa mafanikio.', en: 'Medication saved successfully.' },
  saved_success_title:     { sw: 'Imehifadhiwa', en: 'Saved' },
  delete_title:            { sw: 'Futa dawa?', en: 'Delete medication?' },
  delete_body:             { sw: 'Una uhakika unataka kufuta dawa hii? Kitendo hakiwezi kutenduliwa.', en: 'Are you sure you want to delete this medication? This action cannot be undone.' },
  add_medication:          { sw: 'Ongeza dawa', en: 'Add medication' },
  empty_medications_title: { sw: 'Hakuna dawa', en: 'No medications' },
  empty_medications_sub:   { sw: 'Bonyeza kitufe cha kuongeza dawa mpya.', en: 'Tap the button above to add your first medication.' },
  modal_new_med:           { sw: 'Dawa mpya', en: 'New medication' },
  modal_edit_med:          { sw: 'Hariri dawa', en: 'Edit medication' },
  label_drug_name:         { sw: 'Jina la dawa', en: 'Drug name' },
  label_dosage:            { sw: 'Kipimo', en: 'Dosage' },
  label_frequency:         { sw: 'Mara', en: 'Frequency' },
  label_times:             { sw: 'Nyakati', en: 'Times' },
  label_notes:             { sw: 'Maelezo (optional)', en: 'Notes (optional)' },
  label_source:            { sw: 'Chanzo', en: 'Source' },
  placeholder_drug_name:   { sw: 'Mf. Amoxicillin', en: 'e.g. Amoxicillin' },
  placeholder_dosage:      { sw: 'Mf. 500mg', en: 'e.g. 500mg' },
  placeholder_frequency:   { sw: 'Mf. Mara mbili kwa siku', en: 'e.g. Twice daily' },
  placeholder_times:       { sw: '08:00, 20:00', en: '08:00, 20:00' },
  placeholder_notes:       { sw: 'Mf. Pamoja na chakula', en: 'e.g. With food' },
  times_instruction:       { sw: 'Tenga kwa koma', en: 'Separate with comma' },
  source_manual:           { sw: 'Mkono', en: 'Manual' },
  unknown:                 { sw: 'Haijulikani', en: 'Unknown' },
  adherence_detail:        { sw: 'Maelezo ya Ufuataji', en: 'Adherence Details' },
  source_breakdown:        { sw: 'Vyanzo vya Dawa', en: 'Source Breakdown' },
  source_doctor:           { sw: 'Daktari', en: 'Doctor' },

  // ── Prescription Form Enhancements ──────────────────────────
  freq_once:               { sw: 'Mara moja kwa siku', en: 'Once daily' },
  freq_twice:              { sw: 'Mara mbili kwa siku', en: 'Twice daily' },
  freq_thrice:             { sw: 'Mara tatu kwa siku', en: 'Thrice daily' },
  time_morning:            { sw: 'Asubuhi', en: 'Morning' },
  time_afternoon:          { sw: 'Mchana', en: 'Afternoon' },
  time_evening:            { sw: 'Jioni', en: 'Evening' },
  time_night:              { sw: 'Usiku', en: 'Night' },
  select_times:            { sw: 'Chagua nyakati', en: 'Select times' },
  frequency_presets:       { sw: 'Mara kwa siku', en: 'Per day' },
  time_preset_hint:        { sw: 'Bonyeza kuweka saa', en: 'Tap to set time' },
  no_times_selected:       { sw: 'Chagua angalau wakati mmoja', en: 'Select at least one time' },

  // ── Special Conditions ──────────────────────────────────────
  condition_diabetes:      { sw: 'Kisukari', en: 'Diabetes' },
  condition_bp:            { sw: 'Shinikizo la damu', en: 'Blood Pressure' },
  condition_hiv:           { sw: 'VVU', en: 'HIV' },
  auto_added_title:        { sw: 'Dawa zimeongezwa', en: 'Meds added' },
  auto_added_body:         { sw: 'Dawa za {condition} zimeongezwa kiotomatiki. Unaweza kuzibadilisha.', en: '{condition} medications have been auto-added. You can edit them anytime.' },
  auto_diabetes_rx:        { sw: 'Insulin baada ya kila mlo', en: 'Insulin after each meal' },
  auto_bp_rx:              { sw: 'Dawa ya shinikizo la damu', en: 'Blood pressure medication' },
  auto_hiv_rx:             { sw: 'Tiba ya VVU (ART)', en: 'HIV treatment (ART)' },

  // ── Doctor Screen ───────────────────────────────────────────
  header_doctor:           { sw: 'Daktari', en: 'Doctor' },
  doctor_dashboard:        { sw: 'Dashibodi ya Daktari', en: 'Doctor Dashboard' },
  patient_adherence:       { sw: 'Ufuataji', en: 'Adherence' },
  doses_taken:             { sw: 'Imechukuliwa', en: 'Taken' },
  doses_missed:            { sw: 'Haijachukuliwa', en: 'Missed' },
  recent_activity:         { sw: 'Shughuli za Karibuni', en: 'Recent Activity' },
  no_recent_activity:      { sw: 'Hakuna shughuli za karibuni', en: 'No recent activity' },
  label_patients:          { sw: 'Wagonjwa', en: 'Patients' },
  patient_streak:          { sw: 'Msururu', en: 'Streak' },
  btn_issue_prescription:  { sw: 'Toa dawa', en: 'Issue Prescription' },
  no_patients:             { sw: 'Hakuna wagonjwa waliotengwa.', en: 'No patients assigned yet.' },
  patient_since:           { sw: 'Tangu', en: 'Patient since' },
  select_patient:          { sw: 'Chagua mgonjwa', en: 'Select patient' },
  doctor_notes:            { sw: 'Maelezo ya daktari', en: 'Doctor notes' },
  rx_issued:               { sw: 'Dawa imetolewa kwa mgonjwa.', en: 'Prescription issued to patient.' },
  no_condition_match:      { sw: 'Hali ya kiafya haijatambuliwa kwa dawa za kiotomatiki.', en: 'Condition not recognized for auto-prescriptions.' },

  // ── Voice Notifications ──────────────────────────────────────
  voice_label:             { sw: 'Sauti', en: 'Voice' },
  voice_notif_enabled:     { sw: 'Arifa za sauti zimewashwa', en: 'Voice notifications on' },
  voice_notif_disabled:    { sw: 'Arifa za sauti zimezimwa', en: 'Voice notifications off' },
  notif_time:              { sw: 'Wakati wa kuchukua dawa', en: 'Time to take medication' },
  notif_voice_body:        { sw: 'Ni wakati wa kuchukua {drug}', en: 'Time to take {drug}' },

  // ── Reminders Screen ─────────────────────────────────────────
  header_reminders:        { sw: 'Vikumbusho', en: 'Reminders' },
  status_taken:            { sw: 'Imechukuliwa', en: 'Taken' },
  status_snoozed:          { sw: 'Imeahirishwa', en: 'Snoozed' },
  status_missed:           { sw: 'Imechelewa', en: 'Missed' },
  section_upcoming:        { sw: 'Zinazokuja', en: 'Upcoming' },
  section_earlier:         { sw: 'Za awali', en: 'Earlier today' },
  no_earlier_reminders:    { sw: 'Hakuna vikumbusho vya awali.', en: 'No earlier reminders.' },
  empty_reminders_title:   { sw: 'Hakuna vikumbusho', en: 'No reminders' },
  empty_reminders_sub:     { sw: 'Ongeza dawa katika kichupo cha "Dawa" ili kuunda vikumbusho.', en: 'Add medications in the "Medications" tab to create reminders.' },
  snooze_alert_title:      { sw: 'Kikumbusho', en: 'Reminder' },
  snooze_alert_body:       { sw: 'Tutakukumbusha tena baada ya dakika 5.', en: 'We will remind you again in 5 minutes.' },

  // ── Report Screen ────────────────────────────────────────────
  header_report:           { sw: 'Ripoti', en: 'Report' },
  monthly_adherence:       { sw: 'Uzingativu wa mwezi', en: 'Monthly adherence' },
  heading_weekly_trend:    { sw: 'Mwendo wa wiki', en: 'Weekly Trend' },
  heading_per_med:         { sw: 'Kwa kila dawa', en: 'Per Medication' },
  heading_missed_patterns: { sw: 'Mifumo ya dawa zinazokosa', en: 'Missed Dose Patterns' },
  heading_streak_7day:     { sw: 'Msururu wa siku 7', en: '7-Day Streak' },
  heading_report_history:  { sw: 'Historia ya ripoti', en: 'Report History' },
  heading_share_doctor:    { sw: 'Ungana na daktari', en: 'Share with your doctor' },
  heading_need_help:       { sw: 'Unahitaji msaada?', en: 'Need help?' },
  share_doctor_desc:       { sw: 'Pakua ripoti ya PDF na umwonyeshe daktari wako ili aweze kuelewa hali yako kwa undani.', en: 'Download the PDF report and show it to your doctor so they can understand your condition in detail.' },
  download_report:         { sw: 'Pakua ripoti', en: 'Download report' },
  export_pdf:              { sw: 'Export PDF', en: 'Export PDF' },
  generating:              { sw: 'Inatayarisha...', en: 'Generating...' },
  contact_professional:    { sw: 'Wasiliana na mtaalamu wa afya sasa.', en: 'Contact a health professional now.' },
  share_message:           { sw: 'Ripoti yangu ya afya ya MediSauti', en: 'My MediSauti health report' },
  period_morning:          { sw: 'Asubuhi', en: 'Morning' },
  period_afternoon:        { sw: 'Mchana', en: 'Afternoon' },
  period_evening:          { sw: 'Jioni', en: 'Evening' },
  period_night:            { sw: 'Usiku', en: 'Night' },

  // ── Profile Screen ───────────────────────────────────────────
  header_profile:          { sw: 'Wasifu', en: 'Profile' },
  tap_change_photo:        { sw: 'Bonyeza kubadilisha picha', en: 'Tap to change photo' },
  btn_save_changes:        { sw: 'Hifadhi mabadiliko', en: 'Save Changes' },
  permission_title:        { sw: 'Ruhusa inahitajika', en: 'Permission needed' },
  permission_desc:         { sw: 'Ruhusu ufikiaji wa picha ili kubadilisha picha yako.', en: 'Allow access to photos to change your profile picture.' },
  error_name_required:     { sw: 'Jina linahitajika.', en: 'Name is required.' },
  saved_profile:           { sw: 'Wasifu umehifadhiwa kwa mafanikio.', en: 'Profile updated successfully.' },

  // ── Role Management ─────────────────────────────────────────
  role_patient:            { sw: 'Mgonjwa', en: 'Patient' },
  role_doctor:             { sw: 'Daktari', en: 'Doctor' },
  label_role:              { sw: 'Weka kama', en: 'Register as' },
  label_specialization:    { sw: 'Utaalamu', en: 'Specialization' },
  placeholder_specialization: { sw: 'Mf. Daktari Mkuu', en: 'e.g. General Practitioner' },
  login_as:                { sw: 'Ingia kama', en: 'Login as' },
  switch_role_doctor:      { sw: 'Badilisha kwa Daktari', en: 'Switch to Doctor' },
  switch_role_patient:     { sw: 'Badilisha kwa Mgonjwa', en: 'Switch to Patient' },
  my_doctor:               { sw: 'Daktari wangu', en: 'My Doctor' },
  select_doctor:           { sw: 'Chagua daktari', en: 'Select Doctor' },
  assigned_doctor:         { sw: 'Daktari aliyetengwa', en: 'Assigned Doctor' },
  no_doctor_assigned:      { sw: 'Hajateuliwa', en: 'Not assigned' },
  no_doctors_available:    { sw: 'Hakuna madaktari waliosajiliwa.', en: 'No doctors registered yet.' },
  doctor_register_title:   { sw: 'Usajili wa Daktari', en: 'Doctor Registration' },
  doctor_register_subtitle:{ sw: 'Jaza taarifa zako za kitaalamu.', en: 'Fill in your professional information.' },
  change_doctor:           { sw: 'Badilisha daktari', en: 'Change Doctor' },
};

export default LANG;
