const LANG = {
  // ── Global / Common ──────────────────────────────────────────
  app_name:         { sw: 'MediSauti', en: 'MediSauti' },
  error:            { sw: 'Hitilafu', en: 'Error' },
  success:          { sw: 'Imefanikiwa', en: 'Success' },
  saved:            { sw: 'Imehifadhiwa', en: 'Saved' },
  save:             { sw: 'Hifadhi', en: 'Save' },
  cancel:           { sw: 'Ghairi', en: 'Cancel' },
  delete:           { sw: 'Futa', en: 'Delete' },
  yes:              { sw: 'Ndiyo', en: 'Yes' },
  no:               { sw: 'Hapana', en: 'No' },
  ok:               { sw: 'Sawa', en: 'OK' },
  loading:          { sw: 'Inapakia...', en: 'Loading...' },
  swahili:          { sw: 'Kiswahili', en: 'Swahili' },
  english:          { sw: 'Kiingereza', en: 'English' },

  // ── Days ─────────────────────────────────────────────────────
  mon:              { sw: 'Jnt', en: 'Mon' },
  tue:              { sw: 'Jmn', en: 'Tue' },
  wed:              { sw: 'Jtt', en: 'Wed' },
  thu:              { sw: 'Alh', en: 'Thu' },
  fri:              { sw: 'Ijm', en: 'Fri' },
  sat:              { sw: 'Jum', en: 'Sat' },
  sun:              { sw: 'Jpi', en: 'Sun' },

  // ── Landing Screen ───────────────────────────────────────────
  tagline:          { sw: 'Dawa yako, afya yako', en: 'Your meds, your health' },
  landing_desc:     { sw: 'Panga ratiba ya dawa zako, pata vikumbusho, na fuata uzingativu wako kwa urahisi.', en: 'Schedule your medications, get reminders, and track your adherence easily.' },
  login:            { sw: 'Ingia', en: 'Login' },
  login_sub:        { sw: 'Tumia PIN au alama ya uso', en: 'Use PIN or biometrics' },
  or_divider:       { sw: 'AU', en: 'OR' },
  register:         { sw: 'Jisajili', en: 'Register' },
  register_sub:     { sw: 'Unda akaunti mpya', en: 'Create a new account' },

  // ── Forgot PIN ───────────────────────────────────────────────
  forgot_pin:          { sw: 'Umesahau PIN?', en: 'Forgot PIN?' },
  forgot_pin_title:    { sw: 'Weka upya PIN', en: 'Reset PIN' },
  forgot_pin_phone:    { sw: 'Ingiza namba ya simu ya akaunti yako', en: 'Enter your account phone number' },
  forgot_pin_next:     { sw: 'Endelea', en: 'Next' },
  forgot_pin_code_sent: { sw: 'Msimbo wa uthibitisho umetumwa kwenye simu yako', en: 'A verification code has been sent to your phone' },
  forgot_pin_code_hint: { sw: 'Kwa majaribio, msimbo umeonyeshwa:', en: 'For testing, the code is:' },
  forgot_pin_code_label: { sw: 'Msimbo wa uthibitisho', en: 'Verification code' },
  forgot_pin_new:       { sw: 'Weka PIN mpya (tarakimu 4)', en: 'Set new PIN (4 digits)' },
  forgot_pin_confirm:   { sw: 'Thibitisha PIN mpya', en: 'Confirm new PIN' },
  forgot_pin_btn:       { sw: 'Weka upya', en: 'Reset' },
  forgot_pin_success:   { sw: 'PIN imewekwa upya kwa mafanikio!', en: 'PIN reset successfully!' },
  forgot_pin_no_account:{ sw: 'Hakuna akaunti iliyopatikana kwa namba hii.', en: 'No account found for this number.' },
  forgot_pin_code_wrong:{ sw: 'Msimbo sio sahihi. Jaribu tena.', en: 'Incorrect code. Try again.' },
  forgot_pin_mismatch:  { sw: 'PIN mpya hazilingani.', en: 'New PINs do not match.' },
  forgot_pin_back:      { sw: 'Rudi', en: 'Back' },

  // ── Auth Screen ──────────────────────────────────────────────
  auth_biometric_prompt:   { sw: 'Ingiza alama ya uso au kidole', en: 'Authenticate to continue' },
  auth_use_pin:            { sw: 'Tumia PIN', en: 'Use PIN' },
  bio_opt_in:              { sw: 'Washa kuingia kwa alama ya uso / kidole?', en: 'Enable face / fingerprint login?' },
  bio_opt_in_desc:         { sw: 'Ingia kwa haraka kwa kutumia kifaa chako.', en: 'Log in faster using your device.' },
  bio_enabled_label:       { sw: 'Imewashwa', en: 'Enabled' },
  bio_enabled_desc:        { sw: 'Utatumia alama ya uso / kidole kuingia.', en: 'You will use biometrics to log in.' },
  bio_register_prompt:     { sw: 'Sajili alama ya uso / kidole', en: 'Register face / fingerprint' },
  bio_enrolled:            { sw: 'Imejiandikisha! Sasa utaingia kwa haraka.', en: 'Enrolled! You can now log in faster.' },
  bio_tap_to_login:        { sw: 'Gusa kuingia', en: 'Tap to log in' },
  bio_pref_hint:           { sw: 'Una alama iliyohifadhiwa', en: 'You have biometrics saved' },
  welcome_back:            { sw: 'Karibu tena!', en: 'Welcome back!' },
  fill_all_fields:         { sw: 'Tafadhali jaza sehemu zote.', en: 'Please fill all fields.' },
  pin_mismatch:            { sw: 'PIN hailingani', en: 'PIN Mismatch' },
  pin_mismatch_body:       { sw: 'PIN ulizoingiza hazilingani. Tafadhali jaribu tena.', en: 'The PINs you entered do not match. Please try again.' },
  registration_success:    { sw: 'Umesajiliwa', en: 'Registered' },
  registration_welcome:    { sw: 'Karibu, {name}!', en: 'Welcome, {name}!' },
  invalid_pin:             { sw: 'PIN si sahihi', en: 'Invalid PIN' },
  wrong_pin:               { sw: 'PIN si sahihi', en: 'Wrong PIN' },
  wrong_pin_body:          { sw: 'Umeingiza PIN isiyo sahihi. Tafadhali jaribu tena.', en: 'You entered an incorrect PIN. Please try again.' },
  no_account_found:        { sw: 'Hakuna akaunti iliyopatikana. Tafadhali jisajili kwanza.', en: 'No account found. Please register first.' },
  phone_taken:             { sw: 'Namba hii ya simu tayari imesajiliwa. Tumia namba nyingine.', en: 'This phone number is already registered. Use a different one.' },
  pin_taken:               { sw: 'PIN hii tayari inatumiwa na mtumiaji mwingine. Chagua PIN nyingine.', en: 'This PIN is already used by another user. Choose a different PIN.' },
  card_register_title:     { sw: 'Jisajili', en: 'Register' },
  card_register_subtitle:  { sw: 'Tafadhali jaza taarifa zako za matibabu.', en: 'Please fill in your medical information.' },
  label_name:              { sw: 'Jina kamili', en: 'Full name' },
  label_phone:             { sw: 'Nambari ya simu', en: 'Phone number' },
  label_age:               { sw: 'Umri', en: 'Age' },
  label_condition:         { sw: 'Hali ya kiafya', en: 'Medical condition' },
  label_set_pin:           { sw: 'Weka PIN (tarakimu 4)', en: 'Set PIN (4 digits)' },
  label_confirm_pin:       { sw: 'Thibitisha PIN', en: 'Confirm PIN' },
  label_your_pin:          { sw: 'PIN yako', en: 'Your PIN' },
  btn_register:            { sw: 'Jisajili', en: 'Register' },
  card_login_title:        { sw: 'Ingia', en: 'Login' },
  card_login_subtitle:     { sw: 'Ingiza PIN yako au tumia alama ya uso / kidole.', en: 'Enter your PIN or use face/fingerprint to continue.' },
  btn_biometric:           { sw: 'Tumia alama ya uso / kidole', en: 'Use face / fingerprint' },
  or_enter_pin:            { sw: 'AU ingiza PIN', en: 'OR enter PIN' },
  btn_login:               { sw: 'Ingia', en: 'Login' },
  switch_to_register:      { sw: 'Sajili mtumiaji mpya', en: 'Register a new user' },
  placeholder_name:        { sw: 'Mf. Juma Omary', en: 'e.g. Juma Omary' },
  placeholder_phone:       { sw: 'Mf. 0712345678', en: 'e.g. 0712345678' },
  placeholder_age:         { sw: 'Mf. 30', en: 'e.g. 30' },
  placeholder_condition:   { sw: 'Mf. Kisukari, Shinikizo la damu (tumia koma)', en: 'e.g. Diabetes, Blood Pressure (use comma)' },

  // ── Home Screen ──────────────────────────────────────────────
  greeting_morning:        { sw: 'Habari za asubuhi', en: 'Good morning' },
  greeting_afternoon:      { sw: 'Habari za mchana', en: 'Good afternoon' },
  greeting_evening:        { sw: 'Habari za jioni', en: 'Good evening' },
  greeting_night:          { sw: 'Habari za usiku', en: 'Good night' },
  heading_adherence:       { sw: 'Uzingativu wa mwezi', en: 'Monthly adherence' },
  doses_taken_30d:         { sw: 'Dawa zilizonywa (siku 30)', en: 'Doses taken (30d)' },
  missed_30d:              { sw: 'Zilizokosa (siku 30)', en: 'Missed (30d)' },
  next_reminder:           { sw: 'Inayokuja', en: 'Next reminder' },
  this_week:               { sw: 'Wiki hii', en: 'This week' },
  tip_heading:             { sw: 'Kidokezo', en: 'Tip' },
  tip_text:                { sw: 'Kunywa dawa zako pamoja na chakula ili kupunguza usumbufu wa tumbo.', en: 'Take your meds with food to reduce stomach discomfort.' },
  all_medications:         { sw: 'Dawa zote', en: 'All medications' },
  no_meds_added:           { sw: 'Bado hujaongeza dawa.', en: 'No meds added yet.' },
  badge_low_stock:         { sw: 'Inaisha', en: 'Low stock' },
  badge_active:            { sw: 'Inatumika', en: 'Active' },
  trend_great:             { sw: 'Nzuri', en: 'Great' },
  trend_fair:              { sw: 'Wastani', en: 'Fair' },
  trend_low:               { sw: 'Chini', en: 'Low' },
  taken_label:             { sw: 'zimenywa', en: 'taken' },
  missed_label:            { sw: 'zimekosa', en: 'missed' },
  speaking_reminder:       { sw: '"Ni wakati wa kuchukua dawa yako..."', en: '"It is time to take your medication..."' },
  take_all:                { sw: 'Zote', en: 'All' },

  // ── Scan Screen ──────────────────────────────────────────────
  header_scan:             { sw: 'Changanua', en: 'Scan' },
  hero_title:              { sw: 'Sauti ya Dawa', en: 'Voice of Meds' },
  hero_subtitle:           { sw: 'Changanua lebo yako ya dawa kwa kutumia kamera au ingiza kwa mkono.', en: 'Scan your medication label using the camera or enter it manually.' },
  scanning:                { sw: 'Inasoma...', en: 'Scanning...' },
  ocr_ai_title:            { sw: 'Akili Bandia', en: 'AI Parsing' },
  ocr_ai_no_key:           { sw: 'Hakuna ufunguo wa AI. Inatumia uchambuzi wa mitaa (regex). Weka EXPO_PUBLIC_GEMINI_API_KEY au EXPO_PUBLIC_GITHUB_PAT kwenye .env ili kuwezesha.', en: 'No AI key set. Using local regex parsing. Add EXPO_PUBLIC_GEMINI_API_KEY or EXPO_PUBLIC_GITHUB_PAT to .env to enable.' },
  ready_to_scan:           { sw: 'Tayari kuchanganua', en: 'Ready to scan' },
  manual_entry:            { sw: 'Andika Mwenyewe', en: 'Manual Entry' },
  manual_entry_desc:       { sw: 'Ingiza dawa kwa mkono.', en: 'Type medication details manually.' },
  recent_scans:            { sw: 'Historia', en: 'Recent Scans' },
  recent_scans_desc:       { sw: 'Dawa zilizochanganuliwa hivi karibuni.', en: 'Recently scanned medications.' },
  pro_tip_badge:           { sw: 'USHAURI', en: 'PRO TIP' },
  pro_tip_title:           { sw: 'Hakikisha mwanga mzuri', en: 'Ensure good lighting' },
  pro_tip_desc:            { sw: 'Weka chupa ya dawa kwenye eneo lenye mwanga mzuri na ushikilie simu kwa utulivu kwa matokeo bora.', en: 'Place your medicine bottle in a well-lit area and hold your phone steady for best results.' },

  // ── Prescription Screen ──────────────────────────────────────
  header_medications:      { sw: 'Dawa', en: 'Medications' },
  badge_doctor:            { sw: 'Daktari', en: 'Doctor' },
  validation_error:        { sw: 'Tafadhali jaza jina na kipimo cha dawa.', en: 'Please fill drug name and dosage.' },
  saved_success:           { sw: 'Dawa imehifadhiwa kwa mafanikio.', en: 'Medication saved successfully.' },
  saved_success_title:     { sw: 'Imehifadhiwa', en: 'Saved' },
  delete_title:            { sw: 'Futa dawa?', en: 'Delete medication?' },
  delete_body:             { sw: 'Una uhakika unataka kufuta dawa hii? Kitendo hakiwezi kutenduliwa.', en: 'Are you sure you want to delete this medication? This action cannot be undone.' },
  add_medication:          { sw: 'Ongeza dawa', en: 'Add medication' },
  empty_medications_title: { sw: 'Hakuna dawa', en: 'No medications' },
  empty_medications_sub:   { sw: 'Bonyeza kitufe cha kuongeza dawa mpya.', en: 'Tap the button above to add your first medication.' },
  modal_new_med:           { sw: 'Dawa mpya', en: 'New medication' },
  modal_edit_med:          { sw: 'Hariri dawa', en: 'Edit medication' },
  label_drug_name:         { sw: 'Jina la dawa', en: 'Drug name' },
  label_dosage:            { sw: 'Kipimo', en: 'Dosage' },
  label_frequency:         { sw: 'Mara', en: 'Frequency' },
  label_times:             { sw: 'Nyakati', en: 'Times' },
  label_notes:             { sw: 'Maelezo (optional)', en: 'Notes (optional)' },
  label_source:            { sw: 'Chanzo', en: 'Source' },
  placeholder_drug_name:   { sw: 'Mf. Amoxicillin', en: 'e.g. Amoxicillin' },
  placeholder_dosage:      { sw: 'Mf. 500mg', en: 'e.g. 500mg' },
  placeholder_frequency:   { sw: 'Mf. Mara mbili kwa siku', en: 'e.g. Twice daily' },
  placeholder_times:       { sw: '08:00, 20:00', en: '08:00, 20:00' },
  placeholder_notes:       { sw: 'Mf. Pamoja na chakula', en: 'e.g. With food' },
  times_instruction:       { sw: 'Tenga kwa koma', en: 'Separate with comma' },
  source_manual:           { sw: 'Mkono', en: 'Manual' },
  unknown:                 { sw: 'Haijulikani', en: 'Unknown' },
  adherence_detail:        { sw: 'Maelezo ya Ufuataji', en: 'Adherence Details' },
  source_breakdown:        { sw: 'Vyanzo vya Dawa', en: 'Source Breakdown' },
  source_doctor:           { sw: 'Daktari', en: 'Doctor' },

  // ── Dosage Quantity & Form ──────────────────────────────────
  label_dosage_quantity:   { sw: 'Kiasi cha dozi', en: 'Dosage quantity' },
  label_dosage_form:       { sw: 'Aina ya dawa', en: 'Medication form' },
  placeholder_dosage_qty:  { sw: 'Mf. 1, 2', en: 'e.g. 1, 2' },
  form_tablet:             { sw: 'Kitabu/tableti', en: 'Tablet' },
  form_capsule:            { sw: 'Kapsuli', en: 'Capsule' },
  form_injection:          { sw: 'Sindano', en: 'Injection' },
  form_syrup:              { sw: 'Dawa ya kunywa', en: 'Syrup' },
  form_drops:              { sw: 'Matone', en: 'Drops' },
  form_inhaler:            { sw: 'Vutea', en: 'Inhaler' },
  form_cream:              { sw: 'Krimu', en: 'Cream' },
  form_ointment:           { sw: 'Dawa ya kupaka', en: 'Ointment' },
  form_suppository:        { sw: 'Viashiria', en: 'Suppository' },
  form_patch:              { sw: 'Patchi', en: 'Patch' },
  notif_dosage_detail:     { sw: 'Chukua {qty} {form} ya {drug}', en: 'Take {qty} {form} of {drug}' },
  notif_dosage_simple:     { sw: 'Chukua {drug} {dosage}', en: 'Take {drug} {dosage}' },
  notif_speak_dosage:      { sw: 'Karibu. Ni wakati wa kuchukua {qty} {form} ya {drug}, {timeLabel}. Tafadhali kumbuka kuchukua dawa yako.', en: 'Hello. It is time to take {qty} {form} of {drug}, {timeLabel}. Please remember to take your medicine.' },
  notif_speak_simple:      { sw: 'Karibu. Ni wakati wa kuchukua dawa yako ya {drug}, {dosage}, {timeLabel}. Tafadhali kumbuka kuchukua dawa yako.', en: 'Hello. It is time to take your medication, {drug}, {dosage}. Please remember to take your medicine.' },
  qty_one:                 { sw: 'Moja', en: 'one' },
  qty_two:                 { sw: 'Mbili', en: 'two' },
  qty_three:               { sw: 'Tatu', en: 'three' },
  qty_four:                { sw: 'Nne', en: 'four' },
  qty_five:                { sw: 'Tano', en: 'five' },

  // ── Prescription Form Enhancements ──────────────────────────
  freq_once:               { sw: 'Mara moja kwa siku', en: 'Once daily' },
  freq_twice:              { sw: 'Mara mbili kwa siku', en: 'Twice daily' },
  freq_thrice:             { sw: 'Mara tatu kwa siku', en: 'Thrice daily' },
  time_morning:            { sw: 'Asubuhi', en: 'Morning' },
  time_afternoon:          { sw: 'Mchana', en: 'Afternoon' },
  time_evening:            { sw: 'Jioni', en: 'Evening' },
  time_night:              { sw: 'Usiku', en: 'Night' },
  select_times:            { sw: 'Chagua nyakati', en: 'Select times' },
  frequency_presets:       { sw: 'Mara kwa siku', en: 'Per day' },
  time_preset_hint:        { sw: 'Bonyeza kuweka saa', en: 'Tap to set time' },
  no_times_selected:       { sw: 'Chagua angalau wakati mmoja', en: 'Select at least one time' },

  // ── Special Conditions ──────────────────────────────────────
  condition_diabetes:      { sw: 'Kisukari', en: 'Diabetes' },
  condition_bp:            { sw: 'Shinikizo la damu', en: 'Blood Pressure' },
  condition_hiv:           { sw: 'VVU', en: 'HIV' },
  auto_added_title:        { sw: 'Dawa zimeongezwa', en: 'Meds added' },
  auto_added_body:         { sw: 'Dawa za {condition} zimeongezwa kiotomatiki. Unaweza kuzibadilisha.', en: '{condition} medications have been auto-added. You can edit them anytime.' },
  auto_diabetes_rx:        { sw: 'Insulin baada ya kila mlo', en: 'Insulin after each meal' },
  auto_bp_rx:              { sw: 'Dawa ya shinikizo la damu', en: 'Blood pressure medication' },
  auto_hiv_rx:             { sw: 'Tiba ya VVU (ART)', en: 'HIV treatment (ART)' },

  // ── Doctor Screen ───────────────────────────────────────────
  header_doctor:           { sw: 'Daktari', en: 'Doctor' },
  doctor_dashboard:        { sw: 'Dashibodi ya Daktari', en: 'Doctor Dashboard' },
  patient_adherence:       { sw: 'Ufuataji', en: 'Adherence' },
  doses_taken:             { sw: 'Imechukuliwa', en: 'Taken' },
  doses_missed:            { sw: 'Haijachukuliwa', en: 'Missed' },
  recent_activity:         { sw: 'Shughuli za Karibuni', en: 'Recent Activity' },
  no_recent_activity:      { sw: 'Hakuna shughuli za karibuni', en: 'No recent activity' },
  label_patients:          { sw: 'Wagonjwa', en: 'Patients' },
  patient_streak:          { sw: 'Msururu', en: 'Streak' },
  btn_issue_prescription:  { sw: 'Toa dawa', en: 'Issue Prescription' },
  no_patients:             { sw: 'Hakuna wagonjwa waliotengwa.', en: 'No patients assigned yet.' },
  patient_since:           { sw: 'Tangu', en: 'Patient since' },
  select_patient:          { sw: 'Chagua mgonjwa', en: 'Select patient' },
  doctor_notes:            { sw: 'Maelezo ya daktari', en: 'Doctor notes' },
  rx_issued:               { sw: 'Dawa imetolewa kwa mgonjwa.', en: 'Prescription issued to patient.' },
  no_condition_match:      { sw: 'Hali ya kiafya haijatambuliwa kwa dawa za kiotomatiki.', en: 'Condition not recognized for auto-prescriptions.' },

  // ── Voice Notifications ──────────────────────────────────────
  voice_label:             { sw: 'Sauti', en: 'Voice' },
  voice_notif_enabled:     { sw: 'Arifa za sauti zimewashwa', en: 'Voice notifications on' },
  voice_notif_disabled:    { sw: 'Arifa za sauti zimezimwa', en: 'Voice notifications off' },
  notif_permission_title:  { sw: 'Ruhusa ya arifa', en: 'Notification permission' },
  notif_permission_body:   { sw: 'Tafadhali ruhusu arifa ili kupokea vikumbusho vya dawa zako.', en: 'Please allow notifications to receive medication reminders.' },
  notif_permission_denied: { sw: 'Ruhusa ya arifa imekataliwa. Badilisha katika mipangilio ya simu yako.', en: 'Notification permission was denied. Enable it in your device settings.' },
  notif_permission_granted:{ sw: 'Arifa zimewashwa!', en: 'Notifications enabled!' },
  notif_time:              { sw: 'Wakati wa kuchukua dawa', en: 'Time to take medication' },
  notif_voice_body:        { sw: 'Ni wakati wa kuchukua {drug}', en: 'Time to take {drug}' },
  notif_body_detailed:     { sw: 'Chukua {qty} {form} ya {drug} ({dosage})', en: 'Take {qty} {form} of {drug} ({dosage})' },
  notif_body_simple:       { sw: 'Chukua {drug} {dosage}', en: 'Take {drug} {dosage}' },
  notif_speak_detailed:    { sw: 'Ni wakati wa kuchukua {qty} {form} ya {drug}, {dosage}, {timeLabel}', en: 'Time to take {qty} {form} of {drug}, {dosage}' },
  notif_speak_simple_msg:  { sw: 'Ni wakati wa kuchukua dawa yako ya {drug}, {dosage}', en: 'Time to take your medication, {drug}, {dosage}' },

  // ── Reminders Screen ─────────────────────────────────────────
  header_reminders:        { sw: 'Vikumbusho', en: 'Reminders' },
  status_taken:            { sw: 'Imechukuliwa', en: 'Taken' },
  status_snoozed:          { sw: 'Imeahirishwa', en: 'Snoozed' },
  status_missed:           { sw: 'Imechelewa', en: 'Missed' },
  section_upcoming:        { sw: 'Zinazokuja', en: 'Upcoming' },
  section_earlier:         { sw: 'Za awali', en: 'Earlier today' },
  no_earlier_reminders:    { sw: 'Hakuna vikumbusho vya awali.', en: 'No earlier reminders.' },
  empty_reminders_title:   { sw: 'Hakuna vikumbusho', en: 'No reminders' },
  empty_reminders_sub:     { sw: 'Ongeza dawa katika kichupo cha "Dawa" ili kuunda vikumbusho.', en: 'Add medications in the "Medications" tab to create reminders.' },
  snooze_alert_title:      { sw: 'Kikumbusho', en: 'Reminder' },
  snooze_alert_body:       { sw: 'Tutakukumbusha tena baada ya dakika 5.', en: 'We will remind you again in 5 minutes.' },

  // ── Report Screen ────────────────────────────────────────────
  header_report:           { sw: 'Ripoti', en: 'Report' },
  monthly_adherence:       { sw: 'Uzingativu wa mwezi', en: 'Monthly adherence' },
  heading_weekly_trend:    { sw: 'Mwendo wa wiki', en: 'Weekly Trend' },
  heading_per_med:         { sw: 'Kwa kila dawa', en: 'Per Medication' },
  heading_missed_patterns: { sw: 'Mifumo ya dawa zinazokosa', en: 'Missed Dose Patterns' },
  heading_streak_7day:     { sw: 'Msururu wa siku 7', en: '7-Day Streak' },
  heading_report_history:  { sw: 'Historia ya ripoti', en: 'Report History' },
  heading_share_doctor:    { sw: 'Ungana na daktari', en: 'Share with your doctor' },
  heading_need_help:       { sw: 'Unahitaji msaada?', en: 'Need help?' },
  share_doctor_desc:       { sw: 'Pakua ripoti ya PDF na umwonyeshe daktari wako ili aweze kuelewa hali yako kwa undani.', en: 'Download the PDF report and show it to your doctor so they can understand your condition in detail.' },
  download_report:         { sw: 'Pakua ripoti', en: 'Download report' },
  export_pdf:              { sw: 'Export PDF', en: 'Export PDF' },
  generating:              { sw: 'Inatayarisha...', en: 'Generating...' },
  contact_professional:    { sw: 'Wasiliana na mtaalamu wa afya sasa.', en: 'Contact a health professional now.' },
  share_message:           { sw: 'Ripoti yangu ya afya ya MediSauti', en: 'My MediSauti health report' },
  preview_report:          { sw: 'Angalia ripoti', en: 'Preview report' },
  preview_report_desc:    { sw: 'Angalia ripoti kabla ya kupeana', en: 'Review the report before sharing' },
  preview_share:           { sw: 'Shiriki', en: 'Share' },
  preview_export:          { sw: 'Pakua PDF', en: 'Export PDF' },
  preview_close:           { sw: 'Funga', en: 'Close' },
  preview_title:           { sw: 'Mapitio ya Ripoti', en: 'Report Preview' },
  preview_patient:         { sw: 'Mgonjwa', en: 'Patient' },
  preview_period:          { sw: 'Kipindi', en: 'Period' },
  preview_last_30days:     { sw: 'Siku 30 zilizopita', en: 'Last 30 days' },
  preview_adherence:       { sw: 'Uzingativu', en: 'Adherence' },
  preview_taken:           { sw: 'Imechukuliwa', en: 'Taken' },
  preview_missed:          { sw: 'Imekosa', en: 'Missed' },
  preview_trend:           { sw: 'Mwendo', en: 'Trend' },
  preview_per_med:         { sw: 'Kwa kila dawa', en: 'Per Medication' },
  preview_medications:     { sw: 'Dawa', en: 'Medications' },
  preview_streak:          { sw: 'Msururu wa siku 7', en: '7-Day Streak' },
  preview_generated:       { sw: 'Imetolewa na MediSauti', en: 'Generated by MediSauti' },
  preview_ready_to_share:  { sw: 'Tayari kupeana ripoti', en: 'Ready to share report' },
  period_morning:          { sw: 'Asubuhi', en: 'Morning' },
  period_afternoon:        { sw: 'Mchana', en: 'Afternoon' },
  period_evening:          { sw: 'Jioni', en: 'Evening' },
  period_night:            { sw: 'Usiku', en: 'Night' },

  // ── Profile Screen ───────────────────────────────────────────
  header_profile:          { sw: 'Wasifu', en: 'Profile' },
  tap_change_photo:        { sw: 'Bonyeza kubadilisha picha', en: 'Tap to change photo' },
  btn_save_changes:        { sw: 'Hifadhi mabadiliko', en: 'Save Changes' },
  permission_title:        { sw: 'Ruhusa inahitajika', en: 'Permission needed' },
  permission_desc:         { sw: 'Ruhusu ufikiaji wa picha ili kubadilisha picha yako.', en: 'Allow access to photos to change your profile picture.' },
  error_name_required:     { sw: 'Jina linahitajika.', en: 'Name is required.' },
  saved_profile:           { sw: 'Wasifu umehifadhiwa kwa mafanikio.', en: 'Profile updated successfully.' },
  btn_logout:              { sw: 'Toka', en: 'Log out' },
  logout_confirm_title:    { sw: 'Toka kwenye akaunti', en: 'Log out' },
  logout_confirm_body:     { sw: 'Una uhakika unataka kutoka kwenye akaunti yako? Dawa na rekodi zitabaki kwenye kifaa.', en: 'Are you sure you want to log out? Your medications and records will remain on this device.' },
  change_photo:            { sw: 'Badilisha picha', en: 'Change photo' },

  // ── Role Management ─────────────────────────────────────────
  role_patient:            { sw: 'Mgonjwa', en: 'Patient' },
  role_doctor:             { sw: 'Daktari', en: 'Doctor' },
  label_role:              { sw: 'Weka kama', en: 'Register as' },
  label_specialization:    { sw: 'Utaalamu', en: 'Specialization' },
  placeholder_specialization: { sw: 'Mf. Daktari Mkuu', en: 'e.g. General Practitioner' },
  login_as:                { sw: 'Ingia kama', en: 'Login as' },
  switch_role_doctor:      { sw: 'Badilisha kwa Daktari', en: 'Switch to Doctor' },
  switch_role_patient:     { sw: 'Badilisha kwa Mgonjwa', en: 'Switch to Patient' },
  my_doctor:               { sw: 'Daktari wangu', en: 'My Doctor' },
  select_doctor:           { sw: 'Chagua daktari', en: 'Select Doctor' },
  assigned_doctor:         { sw: 'Daktari aliyetengwa', en: 'Assigned Doctor' },
  no_doctor_assigned:      { sw: 'Hajateuliwa', en: 'Not assigned' },
  no_doctors_available:    { sw: 'Hakuna madaktari waliosajiliwa.', en: 'No doctors registered yet.' },
  doctor_register_title:   { sw: 'Usajili wa Daktari', en: 'Doctor Registration' },
  doctor_register_subtitle:{ sw: 'Jaza taarifa zako za kitaalamu.', en: 'Fill in your professional information.' },
  change_doctor:           { sw: 'Badilisha daktari', en: 'Change Doctor' },

  // ── Dark Mode ────────────────────────────────────────────────
  dark_mode:               { sw: 'Hali ya giza', en: 'Dark mode' },
  light_mode:              { sw: 'Hali ya mwanga', en: 'Light mode' },
  appearance:              { sw: 'Mwonekano', en: 'Appearance' },
  language:                { sw: 'Lugha', en: 'Language' },

  // ── Notifications & Sound ────────────────────────────────────
  notif_settings:        { sw: 'Arifa na Sauti', en: 'Notifications & Sound' },
  notif_permission:      { sw: 'Ruhusa ya arifa', en: 'Notification permission' },
  notif_permission_request: { sw: 'Bonyeza kuwezesha', en: 'Tap to enable' },
  notif_sound:           { sw: 'Sauti ya arifa', en: 'Notification sound' },
  enable:                { sw: 'Washa', en: 'Enable' },
  done:                  { sw: 'Imekamilika', en: 'Done' },
  test_notif:            { sw: 'Jaribu arifa', en: 'Test notification' },
  test_notif_desc:       { sw: 'Tuma arifa ya majaribio na sauti', en: 'Send a test notification with voice' },
  test_notif_sent_title: { sw: 'Jaribio limetumwa', en: 'Test sent' },
  test_notif_sent_body:  { sw: 'Angalia arifa na usikilize sauti ya kikumbusho.', en: 'Check the notification and listen for the voice reminder.' },

  // ── Duration ─────────────────────────────────────────────────
  label_duration:          { sw: 'Muda wa matumizi', en: 'Duration' },
  placeholder_duration:    { sw: 'Mf. 7', en: 'e.g. 7' },
  duration_days:           { sw: 'Siku', en: 'Days' },
  duration_weeks:          { sw: 'Wiki', en: 'Weeks' },
  duration_months:         { sw: 'Miezi', en: 'Months' },

  // ── Prescription Schedule Screen ─────────────────────────────
  header_schedule:         { sw: 'Ratiba ya Dawa', en: 'Prescription Schedule' },
  schedule_title:          { sw: 'Toa Dawa kwa Mgonjwa', en: 'Issue Prescription to Patient' },
  schedule_sub:            { sw: 'Jaza maelezo ya dawa na muda wa matumizi.', en: 'Fill in medication details and duration.' },
  schedule_sent:           { sw: 'Dawa imetolewa kwa ratiba.', en: 'Prescription scheduled successfully.' },
  schedule_duration_label: { sw: 'Muda wa matumizi', en: 'Course Duration' },
  schedule_start_label:    { sw: 'Tarehe ya kuanza', en: 'Start Date' },
  schedule_end_label:      { sw: 'Tarehe ya kuisha', en: 'End Date' },
  schedule_from_today:     { sw: 'Anza leo', en: 'Start today' },
  schedule_specific_date:  { sw: 'Weka tarehe', en: 'Set specific date' },
  schedule_notes_doctor:   { sw: 'Maelezo ya daktari', en: "Doctor's notes" },
  schedule_btn_issue:      { sw: 'Toa Dawa kwa Ratiba', en: 'Issue Scheduled Prescription' },
  schedule_no_patient:     { sw: 'Hakuna mgonjwa aliyeingia. Ingia kama daktari kwanza.', en: 'No patient logged in. Login as doctor first.' },
  schedule_issue_another:  { sw: 'Toa nyingine', en: 'Issue Another' },

  // ── Enhanced Streak ──────────────────────────────────────────
  current_streak:          { sw: 'Msururu wa sasa', en: 'Current Streak' },
  best_streak:             { sw: 'Msururu bora', en: 'Best Streak' },
  days_streak:             { sw: 'siku mfululizo', en: 'days streak' },
  streak_empty:            { sw: 'Bado hakuna msururu. Anza kuchukua dawa zako kwa usawa.', en: 'No streak yet. Start taking your meds consistently.' },
  streak_ongoing:          { sw: 'Unaendelea vizuri!', en: 'Keep it up!' },
  streak_lost:             { sw: 'Msururu umekatika. Anza upya!', en: 'Streak broken. Start again!' },

  // ── Medication Analytics ─────────────────────────────────────
  medication_analytics:    { sw: 'Uchambuzi wa Dawa', en: 'Medication Analytics' },
  adherence_rate:          { sw: 'Kiwango cha ufuataji', en: 'Adherence Rate' },
  total_doses:             { sw: 'Jumla ya dozi', en: 'Total Doses' },
  doses_remaining:         { sw: 'Zimesalia', en: 'Remaining' },
  no_data_analytics:       { sw: 'Hakuna data ya kutosha kwa uchambuzi.', en: 'Not enough data for analytics.' },

  // ── Doctor Analytics ─────────────────────────────────────────
  header_analytics:        { sw: 'Uchambuzi', en: 'Analytics' },
  analytics_total_rx:      { sw: 'Dawa zote', en: 'Total Prescriptions' },
  analytics_active_rx:     { sw: 'Zinazotumika', en: 'Active' },
  analytics_avg_adherence: { sw: 'Wastani wa ufuataji', en: 'Avg Adherence' },
  analytics_current_streak:{ sw: 'Msururu wa sasa', en: 'Current Streak' },
  analytics_by_condition:  { sw: 'Kwa hali ya kiafya', en: 'By Condition' },
  analytics_per_medication:{ sw: 'Kwa kila dawa', en: 'Per Medication' },
  analytics_trend:         { sw: 'Mwendo wa ufuataji', en: 'Adherence Trend' },
  analytics_no_data:       { sw: 'Hakuna data ya kutosha.', en: 'Not enough data.' },
  trend_improving:         { sw: 'Inaongezeka', en: 'Improving' },
  trend_worsening:         { sw: 'Inapungua', en: 'Worsening' },
  trend_stable:            { sw: 'Imetulia', en: 'Stable' },
  trend_insufficient:      { sw: 'Hakuna data', en: 'Insufficient data' },
  condition_other:         { sw: 'Nyingine', en: 'Other' },

  // ── Patient Search ───────────────────────────────────────────
  header_search_patients:  { sw: 'Wagonjwa', en: 'Patients' },
  search_placeholder:      { sw: 'Tafuta kwa jina la dawa au hali...', en: 'Search by drug name or condition...' },
  condition_all:           { sw: 'Wote', en: 'All' },
  no_search_results:       { sw: 'Hakuna matokeo.', en: 'No results found.' },
  tab_analytics:           { sw: 'Uchambuzi', en: 'Analytics' },
  tab_doctor:              { sw: 'Daktari', en: 'Doctor' },
  tab_search:              { sw: 'Tafuta', en: 'Search' },
  patient_record:          { sw: 'Rekodi ya mgonjwa', en: 'Patient Record' },
  btn_schedule:            { sw: 'Ratiba mpya', en: 'New Schedule' },
};

export default LANG;
